libvpx: Explicitly link with pthread support
When building for the native build host, explicitly add the -pthread
option to link against the pthread libraries. This errors like:

  vp9_encoder.c:(.text+0x2073): undefined reference to `pthread_once'

when building the native variant

Ported from commit 6aa414ea0e7258f9ab685934d69e078fc036f1a7
on meta-openembedded:
- Author: Joshua Watt <jpewhacker@gmail.com>
- Date:   Thu Feb 23 08:48:39 2023 -0600

Signed-off-by: Josef Holzmayr <jester@theyoctojester.info>